version: '3'
services:

  user-microservice:
    image: user-microservice
    environment:
      - MY_VAR=old_value
    ports:
      - "9090:9090"
    restart: always
    
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    restart: always